### ISSUE TITLE
[question] How can one connection be used for both the client and the publisher/subscriber?

### ISSUE THREAD

**Issue by SashaYurchenko** [coders51/rabbitmq-stream-js-client#175] opened 2024-01-27 17:56 UTC
Hi guys.

First of all, I'd like to thank you for what you're doing. It's great work!

But I have a question regarding resource usage. I noticed that the `client` and `publisher` (or `consumer`) instances are using two connections to the broker instead of one. This seems quite wasteful in terms of resources. Considering that there can be many services in a, for example, Kubernetes cluster, and all of them will use twice as many connections.

Is it possible to rethink this approach in the future? Or give an optional option for a sender or subscriber to use the same connection that the client creates?

Thanks.

Sample code that demonstrates this:

```ts
  const client = await connect({
    hostname: 'localhost',
    port: 5552,
    username: user,
    password: password,
    vhost: '/',
  });

  await client.createStream({ stream: streamName });

  const publisher = await client.declarePublisher({
    boot: true,
    stream: streamName,
    publisherRef: 'sample-publisher',
  });
```

<img width="709" alt="Screenshot 2024-01-27 at 18 44 33" src="https://github.com/coders51/rabbitmq-stream-js-client/assets/13157397/d28b7fb8-38b3-4bf4-afd0-f894124231a6">

**Comment by tarzacodes** [comment] 2024-01-29 16:06
This is working as intended by design. Each time we create a publisher (or a consumer), we need to check which node is the leader and connect to the leader when it's a publisher and to any other node (if available) if it's a consumer. Connections will be reused if you define multiple publishers to the same node, up to a factor. But we will not reuse connections between consumers, publishers or the first connection, which we named "locator", because we'd risk blocking everything else if, say, a consumer is experiencing pressure. We'd rather have a separate connection so that the runtime can freely switch between them and the user can define new consumers/publishers or publish messages without a single actor monopolizing the resources - the way to implement this was having them on separate connections.
This is not an original idea but rather we drew inspiration from the other clients, namely the C# and Java (the reference implementation) ones: they behave the same.

**Comment by SashaYurchenko** [comment] 2024-01-31 15:37
Thanks a lot for giving such a detailed answer

**Comment by tarzacodes** [comment] 2024-02-01 11:33
Closing the issue because there's nothing to act upon, but thanks for reaching out! We're always happy to interact with the community :partying_face:

**Closed by tarzacodes** 2024-02-01 11:33 UTC
